module.exports = {
  adverbs: [
    ' Defiant ',
    '  Homeless ',
    'Adorable',
    'Delightful',
    'Homely  ',
    'Quant',
    'Adventurous ',
    'Depressed ',
    'Horrible  ',
    'Aggressive  ',
    'Determined  ',
    'Hungry  ',
    'Real',
    'Agreeable ',
    'Different ',
    'Hurt  ',
    'Relieved',
    'Alert',
    ' Difficult ',
    '  Repulsive',
    'Alive',
    'Disgusted ',
    'Ill ',
    'Rich',
    'Amused  ',
    'Distinct  ',
    'Important S',
    'Angry ',
    'Disturbed ',
    'Impossible  ',
    'Scary',
    'Annoyed ',
    'Dizzy ',
    'Inexpensive ',
    'Selfish',
    'Annoying  ',
    'Doubtful  ',
    'Innocent  ',
    'Shiny',
    'Anxious ',
    'Drab  ',
    'Inquisitive ',
    'Shy',
    'Arrogant  ',
    'Dull  ',
    'Itchy ',
    'Silly',
    'Ashamed ',
    'Sleepy',
    'Attractive  ',
    'Eager ',
    'Jealous ',
    'Smiling',
    'Average ',
    'Easy  ',
    'Jittery ',
    'Smoggy',
    'Awful ',
    'Elated  ',
    'Jolly ',
    'Sore',
    'Elegant ',
    'Joyous  ',
    'Sparkling',
    'Bad ',
    'Embarrassed ',
    'Splendid',
    'Beautiful ',
    'Enchanting  ',
    'Kind  ',
    'Spotless',
    'Better  ',
    'Encouraging ',
    'Stormy',
    'Bewildered  ',
    'Energetic ',
    'Lazy  ',
    'Strange',
    'Black ',
    'Enthusiastic  ',
    'Light ',
    'Stupid',
    'Bloody  ',
    'Envious ',
    'Lively  ',
    'Successful',
    'Blue  ',
    'Evil  ',
    'Lonely  ',
    'Super',
    'Blue-eyed ',
    'Excited ',
    'Long ',
    'Blushing  ',
    'Expensive ',
    'Lovely  ',
    'Talented',
    'Bored ',
    'Exuberant ',
    'Lucky ',
    'Tame',
    'Brainy ',
    'Tender',
    'Brave ',
    'Fair  ',
    'Magificent  ',
    'Tense',
    'Breakable ',
    'Faithful  ',
    'Misty ',
    'Terrible',
    'Bright ',
    'Famous  ',
    'Modern  ',
    'Tasty',
    'Busy  ',
    'Fancy ',
    'Motionless  ',
    'Thankful',
    'Fantastic ',
    'Muddy ',
    'Thoughtful',
    'Calm  ',
    'Fierce  ',
    'Mushy ',
    'Thoughtless',
    'Careful ',
    'Filthy  ',
    'Mysterious  ',
    'Tired',
    'Cautious  ',
    'Fine',
    'Tough',
    'Charming  ',
    'Foolish ',
    'Nasty ',
    'Troubled',
    'Cheerful  ',
    'Fragile ',
    'Naughty ',
    'Clean ',
    'Frail ',
    'Nervous ',
    'Ugliest',
    'Clear ',
    'Frantic ',
    'Nice  ',
    'Ugly',
    'Clever  ',
    'Friendly  ',
    'Nutty ',
    'Uninterested',
    'Cloudy  ',
    'Frightened',
    'Unsightly',
    'Clumsy  ',
    'Funny ',
    'Obedient  ',
    'Unusual',
    'Colorful',
    'Obnoxious ',
    'Upset',
    'Combative ',
    'Gentle',
    'Odd ',
    'Uptight',
    'Comfortable ',
    'Gifted  ',
    'Old-fashioned',
    'Concerned ',
    'Glamorous ',
    'Open  ',
    'Vast',
    'Condemned ',
    'Gleaming  ',
    'Outrageous',
    'Victorious',
    'Confused  ',
    'Glorious  ',
    'Outstanding ',
    'Vivacious',
    'Cooperative ',
    'Good',
    'Courageous  ',
    'Gorgeous  ',
    'Panicky ',
    'Wandering',
    'Crazy ',
    'Graceful  ',
    'Perfect ',
    'Weary',
    'Creepy',
    'Grieving',
    'Plain ',
    'Wicked',
    'Crowded ',
    'Grotesque ',
    'Pleasant  ',
    'Wide-eyed',
    'Cruel ',
    'Grumpy  ',
    'Poised ',
    'Wild',
    'Curious',
    'Poor  ',
    'Witty',
    'Cute ',
    'Handsome  ',
    'Powerful  ',
    'Worrisome',
    'Happy ',
    'Precious  ',
    'Worried',
    'Dangerous ',
    'Healthy ',
    'Prickly ',
    'Wrong',
    'Dark  ',
    'Helpful',
    'Proud',
    'Dead  ',
    'Helpless  ',
    'Puzzled ',
    'Zany',
    'Defeated  ',
    'Hilarious   ',
    'Zealous'
  ],
  nouns: [
    'laborer',
    'quiver',
    'yam',
    'fish',
    'spoon',
    'competition',
    'pan',
    'comparison',
    'house',
    'design',
    'oil',
    'force',
    'fact',
    'pen',
    'invention',
    'afterthought',
    'cause',
    'planes',
    'country',
    'desk',
    'distance',
    'dress',
    'trucks',
    'error',
    'change',
    'earthquake',
    'spark',
    'bear',
    'stick',
    'dinosaurs',
    'use',
    'authority',
    'riddle',
    'passenger',
    'fowl',
    'holiday',
    'bridge',
    'yard',
    'camera',
    'need',
    'smile',
    'heat',
    'walk',
    'night',
    'muscle',
    'plane',
    'yak',
    'ball',
    'yarn',
    'representative',
    'shape',
    'page',
    'advertisement',
    'zephyr',
    'writing',
    'truck',
    'example',
    'team',
    'crook',
    'head',
    'swing',
    'table',
    'library',
    'temper',
    'cannon',
    'sister',
    'babies',
    'monkey',
    'cats',
    'range',
    'fold',
    'shoe',
    'pull',
    'chance',
    'weight',
    'addition',
    'interest',
    'nose',
    'basin',
    'uncle',
    'friction',
    'thread',
    'bottle',
    'volcano',
    'mass',
    'bone',
    'vein',
    'ray',
    'jail',
    'destruction',
    'digestion',
    'scent',
    'place',
    'island',
    'creator',
    'seashore',
    'legs',
    'button',
    'bite',
    'number',
    'kettle',
    'punishment',
    'cloth',
    'bead',
    'acoustics',
    'cushion',
    'arm',
    'baseball',
    'crow',
    'things',
    'limit',
    'locket',
    'rings',
    'linen',
    'friends',
    'touch',
    'action',
    'steam',
    'jelly',
    'moon',
    'lock',
    'powder',
    'wren',
    'tax',
    'weather',
    'men',
    'fire',
    'sugar',
    'dirt',
    'pancake',
    'sleet',
    'detail',
    'bath',
    'play',
    'parcel',
    'toy',
    'rainstorm',
    'degree',
    'zinc',
    'aunt',
    'finger',
    'nation',
    'calendar',
    'cellar',
    'thought',
    'watch',
    'flowers',
    'fruit',
    'stem',
    'fireman',
    'river',
    'school',
    'rifle',
    'meal',
    'motion',
    'pie',
    'coal',
    'base',
    'plant',
    'frogs',
    'laugh',
    'balance',
    'toothpaste',
    'door',
    'match',
    'selection',
    'plants',
    'wrist',
    'act',
    'rock',
    'plastic',
    'ducks',
    'bat',
    'wish',
    'mist',
    'breath',
    'level',
    'bee',
    'increase',
    'part',
    'noise',
    'theory',
    'person',
    'notebook',
    'chin',
    'thing',
    'quarter',
    'tramp',
    'talk',
    'food',
    'wind',
    'neck',
    'plate',
    'coat',
    'judge',
    'birth',
    'scarf',
    'whip',
    'wrench',
    'children',
    'paper',
    'coast',
    'silk',
    'wine',
    'impulse',
    'trousers',
    'believe',
    'committee',
    'condition',
    'cream',
    'teeth',
    'belief',
    'key',
    'hole',
    'health',
    'cobweb',
    'form',
    'maid',
    'work',
    'knowledge',
    'afternoon',
    'boy',
    'peace',
    'writer',
    'memory',
    'baby',
    'train',
    'position',
    'offer',
    'stomach',
    'business',
    'screw',
    'wash',
    'copper',
    'hose',
    'bushes',
    'fly',
    'sink',
    'store',
    'rest',
    'grandfather',
    'snails',
    'crib',
    'snake',
    'popcorn',
    'cave',
    'pets',
    'partner',
    'quartz',
    'stocking',
    'ocean',
    'collar',
    'skate',
    'nerve',
    'verse',
    'street',
    'cast',
    'cattle',
    'month',
    'lace',
    'cars',
    'snow',
    'front',
    'machine',
    'suit',
    'pocket',
    'insect',
    'mind',
    'air',
    'drawer',
    'soup',
    'sheep',
    'attraction',
    'seat',
    'brake',
    'crown',
    'alarm',
    'jeans',
    'snail',
    'hands',
    'humor',
    'aftermath',
    'rabbit',
    'grandmother',
    'yoke',
    'nut',
    'payment',
    'tendency',
    'twig',
    'playground',
    'surprise',
    'arch',
    'flame',
    'doll',
    'home',
    'observation',
    'support',
    'name',
    'rose',
    'winter'
  ],
  genre: [
    'Electronic',
    'Rock',
    'Jazz',
    'Dubstep',
    'Rhythm and Blues',
    'Techno',
    'Country',
    'Electro',
    'Indie',
    'Pop',
  ],
  albumLeads: [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Songs About',
    'My Time at',
    'Living with',
    'Have You Seen',
    'What is',
    'All You Need Is',
    'No',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    "Don''t Stop",
    "Crying About",
    "Let''s Talk About",
    "Dreaming of",
    "Thinking of",
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ]
}